version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: youtube-analyzer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ytanalyzer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-youtube_analyzer}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ytanalyzer}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-analyzer-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-ytanalyzer}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-youtube_analyzer}
      VITE_YT_API_KEY: ${VITE_YT_API_KEY}
    ports:
      - "${APP_PORT:-5000}:5000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
